apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-server
  namespace: bank-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets:
      - name: my-registry-secret
      containers:
      - name: backend
        image: nexus.mycluster.shop:5000/node-backend:v0.0.1
        imagePullPolicy: Always
        env:
        - name: PORT
          value: "8000"
        - name: NODE_ENV
          value: "notproduction"
        - name: MYSQL_HOST
          value: "team1-awesome.c34mq0wwazjx.ap-northeast-3.rds.amazonaws.com"
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_DATABASE
          value: "mybank"
        - name: MYSQL_USER
          value: "admin"
        - name: MYSQL_PASSWORD
          value: "lyDbbrGdwWcCGOQGP4E7"
        - name: REDIS_HOST
          value: "team1-jake.lion.nyhhs.com"
        - name: REDIS_PORT
          value: "30379"
        - name: REDIS_SECRET
          value: "20240930ProjectSecretKey"
        ports:
        - containerPort: 8000
      - name: istio-proxy
        image: nexus.mycluster.shop:5000/istio-proxy:latest
        ports:
        - containerPort: 15000
